name: Build gd-edit executable

on:
  workflow_dispatch:
  push:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '8'

      - uses: DeLaGuardo/setup-clojure@13
        with:
          cli: latest

      - name: Install launch4j
        run: |
          sudo apt-get update && sudo apt-get install -y dos2unix
          curl -L -o launch4j.tgz "https://sourceforge.net/projects/launch4j/files/launch4j-3/3.50/launch4j-3.50-linux-x64.tgz/download"
          sudo tar -xzf launch4j.tgz -C /opt
          sudo dos2unix /opt/launch4j/launch4j
          sudo chmod +x /opt/launch4j/launch4j
          echo "/opt/launch4j" >> $GITHUB_PATH

      - name: Build
        run: clojure -T:build build

      - uses: actions/upload-artifact@v4
        with:
          name: gd-edit-build
          path: |
            target/*.exe
            target/gd-edit
